"""empty message

Revision ID: 5a09f947db8a
Revises: 
Create Date: 2024-03-01 17:15:55.526473

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a09f947db8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'url_map',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('original', sa.String(length=256), nullable=False),
        sa.Column('short', sa.String(length=24), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_url_map_timestamp'), 'url_map', ['timestamp'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_map_timestamp'), table_name='url_map')
    op.drop_table('url_map')
    # ### end Alembic commands ###
